"""Rule metadata for the Python AST analyzer (detection logic lives in python_analyzer.py)."""

from __future__ import annotations

from netguard.enums import Confidence as C
from netguard.enums import Severity as S
from netguard.scanners.sast.rules import Rule, owasp

PY = ("python",)


def _r(
    id_: str,
    title: str,
    cat: str,
    sev: S,
    conf: C,
    cwe: str,
    desc: str,
    impact: str,
    fix: str,
    *,
    expl: str = "medium",
    fixer: str = "",
    refs: tuple[str, ...] = (),
) -> Rule:
    return Rule(
        id=id_,
        title=title,
        category=cat,
        severity=sev,
        confidence=conf,
        cwe=cwe,
        languages=PY,
        description=desc,
        impact=impact,
        remediation=fix,
        exploitability=expl,
        fixer=fixer,
        references=refs,
    )


PY_RULES: dict[str, Rule] = {
    r.id: r
    for r in [
        _r(
            "py.sql-injection",
            "SQL query built with string formatting",
            "SQL Injection",
            S.HIGH,
            C.MEDIUM,
            "CWE-89",
            "A SQL statement is built with f-strings, concatenation, % or .format() and passed to "
            "the database.",
            "An attacker can change the query logic to read, modify or delete data.",
            "Use parameterized queries: cursor.execute('SELECT ... WHERE id = %s', (user_id,)), or "
            "an ORM's bound parameters.",
            expl="high",
            refs=(owasp("attacks/SQL_Injection"),),
        ),
        _r(
            "py.command-injection",
            "OS command built from dynamic input",
            "Command Injection",
            S.HIGH,
            C.MEDIUM,
            "CWE-78",
            "A shell command is executed with a dynamically built string (os.system, os.popen or "
            "subprocess with shell=True).",
            "Attacker-controlled input can inject commands and run arbitrary code as the "
            "application user.",
            "Use subprocess.run([...], shell=False) with an argument list, and validate inputs "
            "against an allow-list. Use shlex.quote only as a last resort.",
            expl="high",
            refs=(owasp("attacks/Command_Injection"),),
        ),
        _r(
            "py.subprocess-shell-true",
            "subprocess called with shell=True",
            "Command Injection",
            S.LOW,
            C.MEDIUM,
            "CWE-78",
            "subprocess is invoked with shell=True on a constant command.",
            "Currently not injectable, but any later change that adds variables to the string "
            "creates command injection.",
            "Pass the command as an argument list and drop shell=True.",
            expl="low",
        ),
        _r(
            "py.code-injection",
            "Dynamic code execution (eval/exec)",
            "Code Injection",
            S.HIGH,
            C.MEDIUM,
            "CWE-95",
            "eval()/exec()/compile() run text as Python code.",
            "If any part of the string is attacker-controlled, they can execute arbitrary Python.",
            "Use ast.literal_eval for literals, json.loads for data, or explicit dispatch tables.",
            expl="high",
        ),
        _r(
            "py.unsafe-deserialization",
            "Unsafe deserialization",
            "Unsafe Deserialization",
            S.HIGH,
            C.MEDIUM,
            "CWE-502",
            "pickle/marshal/dill/unsafe YAML loaders can execute code while deserializing.",
            "Deserializing untrusted data leads to remote code execution.",
            "Use json or yaml.safe_load for untrusted data. Never unpickle data from outside your "
            "trust boundary; sign and verify it if unavoidable.",
            expl="high",
            fixer="py.unsafe-deserialization",
            refs=(owasp("vulnerabilities/Deserialization_of_untrusted_data"),),
        ),
        _r(
            "py.weak-hash",
            "Weak hash algorithm (MD5 / SHA-1)",
            "Insecure Cryptography",
            S.MEDIUM,
            C.HIGH,
            "CWE-327",
            "MD5/SHA-1 are cryptographically broken and fast to brute-force.",
            "Integrity checks can be forged and password hashes cracked quickly.",
            "Use hashlib.sha256/sha3 for integrity, and a password hash (argon2, bcrypt, scrypt) "
            "for passwords. Pass usedforsecurity=False for non-security uses.",
            expl="low",
            fixer="py.weak-hash",
        ),
        _r(
            "py.weak-cipher",
            "Weak or unsafe cipher / mode",
            "Insecure Cryptography",
            S.MEDIUM,
            C.HIGH,
            "CWE-327",
            "DES/RC4/Blowfish or AES in ECB mode is used.",
            "Ciphertext can be decrypted or patterns revealed.",
            "Use AES-GCM or ChaCha20-Poly1305 via the 'cryptography' library.",
            expl="low",
        ),
        _r(
            "py.insecure-random",
            "Non-cryptographic random used for a secret",
            "Insecure Randomness",
            S.MEDIUM,
            C.MEDIUM,
            "CWE-338",
            "The random module is not suitable for tokens, keys, salts or passwords.",
            "Values can be predicted, allowing account takeover or forged tokens.",
            "Use the secrets module (secrets.token_urlsafe, secrets.token_hex) or os.urandom.",
            fixer="py.insecure-random",
        ),
        _r(
            "py.tls-verification-disabled",
            "TLS certificate verification disabled",
            "Insecure Transport",
            S.HIGH,
            C.HIGH,
            "CWE-295",
            "Certificate validation is turned off for an HTTPS connection.",
            "The connection can be intercepted and modified (man-in-the-middle).",
            "Remove verify=False / CERT_NONE and configure the correct CA bundle.",
            expl="medium",
            fixer="py.tls-verification-disabled",
        ),
        _r(
            "py.debug-enabled",
            "Debug mode enabled",
            "Security Misconfiguration",
            S.HIGH,
            C.HIGH,
            "CWE-489",
            "The Flask/Werkzeug or Django debugger is enabled in code.",
            "The interactive debugger permits remote code execution and leaks source and settings.",
            "Never enable debug in production; drive it from an environment variable that defaults "
            "to off.",
            expl="medium",
            fixer="py.debug-enabled",
        ),
        _r(
            "py.path-traversal",
            "File path built from user input",
            "Path Traversal",
            S.HIGH,
            C.MEDIUM,
            "CWE-22",
            "A filesystem call receives a path that originates from request data.",
            "Using ../ sequences, an attacker can read or overwrite files outside the intended folder.",
            "Use werkzeug.utils.secure_filename, resolve the path and confirm it stays inside an "
            "allowed base directory, or use server-side IDs.",
            expl="high",
            refs=(owasp("attacks/Path_Traversal"),),
        ),
        _r(
            "py.archive-extraction",
            "Archive extracted without path validation",
            "Path Traversal",
            S.MEDIUM,
            C.LOW,
            "CWE-22",
            "extractall() is called without a filter or member validation.",
            "A crafted archive can write files outside the destination (zip-slip / tar traversal).",
            "Validate every member path, or on Python 3.12+ use tarfile.extractall(filter='data').",
            expl="low",
        ),
        _r(
            "py.ssrf",
            "Outbound request to a user-controlled URL",
            "Server-Side Request Forgery",
            S.HIGH,
            C.MEDIUM,
            "CWE-918",
            "The server fetches a URL that comes from request data.",
            "Attackers can reach internal services or cloud metadata endpoints through your server.",
            "Allow-list destination hosts, resolve and block private/link-local addresses, and "
            "disable redirects.",
            expl="medium",
        ),
        _r(
            "py.template-injection",
            "Server-side template built from user input",
            "Template Injection",
            S.CRITICAL,
            C.HIGH,
            "CWE-1336",
            "render_template_string()/Template() receives request-controlled text.",
            "Jinja2 template injection leads to remote code execution.",
            "Render static templates and pass user input only as context variables.",
            expl="high",
        ),
        _r(
            "py.reflected-xss",
            "Unescaped user input marked safe / returned as HTML",
            "Cross-Site Scripting",
            S.HIGH,
            C.MEDIUM,
            "CWE-79",
            "Request data is wrapped in Markup()/mark_safe() or returned in an HttpResponse.",
            "Script injected via the input runs in other users' browsers.",
            "Let the template engine auto-escape, or escape explicitly (markupsafe.escape).",
            expl="high",
        ),
        _r(
            "py.open-redirect",
            "Redirect to a user-controlled URL",
            "Open Redirect",
            S.MEDIUM,
            C.MEDIUM,
            "CWE-601",
            "redirect() is called with a value from the request.",
            "Enables phishing through a trusted domain.",
            "Redirect only to relative paths or an allow-list; use url_has_allowed_host_and_scheme.",
            expl="medium",
        ),
        _r(
            "py.insecure-tempfile",
            "Insecure temporary file (mktemp)",
            "Insecure File Operations",
            S.MEDIUM,
            C.HIGH,
            "CWE-377",
            "tempfile.mktemp() returns a name without creating the file, creating a race condition.",
            "An attacker can pre-create a symlink at the predicted path and hijack writes.",
            "Use tempfile.mkstemp(), NamedTemporaryFile() or TemporaryDirectory().",
            expl="low",
            fixer="py.insecure-tempfile",
        ),
        _r(
            "py.xxe",
            "XML parsed from user input without hardening",
            "XML External Entity",
            S.MEDIUM,
            C.MEDIUM,
            "CWE-611",
            "An XML parser receives request-controlled data.",
            "Entity expansion can read local files or exhaust memory.",
            "Use defusedxml, or disable DTD/entity resolution in the parser.",
            expl="medium",
        ),
        _r(
            "py.hardcoded-credential-check",
            "Credential compared to a hard-coded value",
            "Insecure Authentication",
            S.HIGH,
            C.MEDIUM,
            "CWE-798",
            "Authentication logic compares a password/token against a literal in code.",
            "Anyone with the source can authenticate; the credential cannot be rotated without a deploy.",
            "Store salted password hashes in a datastore or secret manager and compare with a "
            "constant-time function.",
            expl="high",
        ),
        _r(
            "py.jwt-insecure",
            "Insecure JWT verification",
            "Insecure Authentication",
            S.HIGH,
            C.HIGH,
            "CWE-347",
            "JWT signature verification is disabled or the 'none' algorithm is accepted.",
            "Attackers can forge tokens and impersonate any user.",
            "Always verify the signature with a pinned algorithm list.",
            expl="high",
        ),
        _r(
            "py.csrf-exempt",
            "CSRF protection disabled on a view",
            "Authorization",
            S.MEDIUM,
            C.LOW,
            "CWE-352",
            "@csrf_exempt removes Django's CSRF protection for the view.",
            "State-changing requests can be forged from another site if the view uses cookie auth.",
            "Remove the decorator or authenticate the endpoint with tokens instead of cookies.",
            expl="medium",
        ),
        _r(
            "py.permission-allow-any",
            "Endpoint open to everyone (AllowAny)",
            "Authorization",
            S.LOW,
            C.LOW,
            "CWE-862",
            "A Django REST Framework view uses AllowAny permissions.",
            "The endpoint has no authorization; ensure this is intentional.",
            "Use IsAuthenticated (or a stricter permission) unless the endpoint is meant to be public.",
            expl="low",
        ),
        _r(
            "py.insecure-cookie",
            "Cookie without Secure/HttpOnly",
            "Insecure Authentication",
            S.MEDIUM,
            C.MEDIUM,
            "CWE-614",
            "A cookie protection flag is explicitly disabled.",
            "Scripts can read the cookie or it can travel over plaintext HTTP.",
            "Set secure=True, httponly=True and samesite='Lax' or 'Strict'.",
            expl="medium",
        ),
        _r(
            "py.file-permissions",
            "Overly permissive file mode",
            "Insecure File Operations",
            S.MEDIUM,
            C.HIGH,
            "CWE-732",
            "A file is made world-writable (0o777/0o666) or the umask is cleared.",
            "Other local users can modify or replace the file.",
            "Use the least permissive mode needed (0o600 files, 0o700 directories).",
            expl="low",
        ),
    ]
}
