"""Go, PHP, Ruby and shell rules."""

from __future__ import annotations

import re

from netguard.enums import Confidence as C
from netguard.enums import Severity as S
from netguard.scanners.sast.rules import Rule, rx

I = re.IGNORECASE  # noqa: E741
GO, PHP, RB, SH = ("go",), ("php",), ("ruby",), ("shell",)
_SQL = r"\b(?:select|insert\s+into|update|delete\s+from)\b"
_SECRET_WORDS = r"(?=.*(?:token|secret|password|passwd|session|nonce|apikey|api_key|csrf|salt))"
_PHP_IN = r"\$_(?:GET|POST|REQUEST|COOKIE|FILES|SERVER)"


def mk(id_, title, cat, sev, conf, cwe, langs, pattern, desc, impact, fix, *, flags=0,
       unless=None, expl="medium", refs=()):
    return Rule(
        id=id_, title=title, category=cat, severity=sev, confidence=conf, cwe=cwe,
        languages=langs, pattern=rx(pattern, flags), unless=rx(unless, flags) if unless else None,
        description=desc, impact=impact, remediation=fix, exploitability=expl, references=refs,
    )


RULES: list[Rule] = [
    # ---- Go -------------------------------------------------------------------------------
    mk("go.sql-injection", "SQL query built with fmt.Sprintf / concatenation", "SQL Injection",
       S.HIGH, C.MEDIUM, "CWE-89", GO,
       rf"(?:Query|QueryRow|Exec|Prepare)\w*\(\s*(?:\w+,\s*)?(?:fmt\.Sprintf\(\s*\"[^\"]*{_SQL}|"
       rf"\"[^\"]*{_SQL}[^\"]*\"\s*\+)",
       "A SQL statement is formatted from variables before being executed.",
       "An attacker can modify the query.",
       "Use placeholders: db.Query(\"SELECT ... WHERE id = $1\", id).", flags=I, expl="high"),
    mk("go.command-injection", "Command executed through a shell with dynamic input",
       "Command Injection", S.HIGH, C.MEDIUM, "CWE-78", GO,
       r"exec\.Command(?:Context)?\(\s*(?:\w+,\s*)?\"(?:sh|bash|cmd(?:\.exe)?)\"\s*,\s*"
       r"\"(?:-c|/c)\"\s*,\s*[^\"\s]",
       "A shell is invoked with a command string that includes variables.",
       "Input can inject additional commands.",
       "Call the program directly with separate arguments (exec.Command(\"ls\", dir)).",
       expl="high"),
    mk("go.tls-verification-disabled", "TLS verification disabled (InsecureSkipVerify)",
       "Insecure Transport", S.HIGH, C.HIGH, "CWE-295", GO, r"InsecureSkipVerify\s*:\s*true",
       "Certificate chain and hostname verification are skipped.",
       "Connections can be intercepted.", "Remove InsecureSkipVerify and configure RootCAs.",
       expl="medium"),
    mk("go.weak-hash", "Weak hash algorithm (MD5 / SHA-1)", "Insecure Cryptography", S.MEDIUM,
       C.HIGH, "CWE-327", GO, r"\b(?:md5|sha1)\.(?:New|Sum)\s*\(",
       "MD5/SHA-1 are broken.", "Hashes can be forged; passwords cracked.",
       "Use crypto/sha256 (or sha512), and bcrypt/argon2 for passwords.", expl="low"),
    mk("go.insecure-random", "math/rand used for a secret", "Insecure Randomness", S.MEDIUM,
       C.MEDIUM, "CWE-338", GO, rf"{_SECRET_WORDS}.*\brand\.(?:Int|Intn|Int63|Int31|Read|Seed)\w*\(",
       "math/rand is deterministic and predictable.", "Tokens/keys can be guessed.",
       "Use crypto/rand.", flags=I),
    mk("go.path-traversal", "File path built from request input", "Path Traversal", S.HIGH,
       C.MEDIUM, "CWE-22", GO,
       r"(?:os\.(?:Open|ReadFile|Remove|Create)|ioutil\.ReadFile|filepath\.Join|http\.ServeFile)"
       r"\s*\([^;]*(?:r\.URL\.Query\(\)|r\.FormValue|\.Query\(\)\.Get|c\.Param|c\.Query|r\.PostFormValue)",
       "A filesystem call receives a path from request input.",
       "Attackers can read files outside the intended directory.",
       "Use filepath.Clean and verify the result stays in a base directory (or http.Dir/FS).",
       expl="high"),
    mk("go.ssrf", "Outbound request to a URL from the request", "Server-Side Request Forgery",
       S.HIGH, C.MEDIUM, "CWE-918", GO,
       r"http\.(?:Get|Post|Head)\s*\(\s*(?:r\.FormValue|r\.URL\.Query|c\.Query|c\.Param)",
       "The server fetches a client-supplied URL.",
       "Attackers can reach internal services or metadata endpoints.",
       "Allow-list destinations and block private/link-local addresses."),
    mk("go.template-html", "Unescaped HTML via template.HTML", "Cross-Site Scripting", S.MEDIUM,
       C.LOW, "CWE-79", GO, r"\btemplate\.(?:HTML|JS|URL)\s*\(",
       "template.HTML() marks a string as safe, bypassing html/template escaping.",
       "Untrusted content becomes executable in the browser.",
       "Pass plain strings to templates and let html/template escape them."),
    # ---- PHP --------------------------------------------------------------------------------
    mk("php.eval", "Use of eval()", "Code Injection", S.HIGH, C.MEDIUM, "CWE-95", PHP,
       r"\beval\s*\(\s*(?![\"'][^\"'$]*[\"']\s*\))",
       "eval() executes a string as PHP code.",
       "Attacker-controlled input gives remote code execution.",
       "Remove eval(); use explicit logic or a safe expression evaluator.", expl="high"),
    mk("php.command-injection", "OS command built from variables", "Command Injection", S.HIGH,
       C.MEDIUM, "CWE-78", PHP,
       rf"\b(?:system|exec|shell_exec|passthru|popen|proc_open)\s*\([^;]*(?:{_PHP_IN}|\$\w+)",
       "A shell command is built from variables or request data.",
       "Input can inject additional commands.",
       "Use escapeshellarg() on every argument and prefer native PHP functions.",
       expl="high"),
    mk("php.sql-injection", "SQL query built from variables", "SQL Injection", S.HIGH, C.MEDIUM,
       "CWE-89", PHP,
       rf"(?:mysql_query|mysqli_query|pg_query|->query|->exec)\s*\([^;]*(?:{_PHP_IN}|\"[^\"]*\"\s*\.\s*\$|\"[^\"]*{_SQL}[^\"]*\$\w+)",
       "A SQL statement includes variables or request data directly.",
       "An attacker can alter the query.",
       "Use PDO/mysqli prepared statements with bound parameters.", flags=I, expl="high"),
    mk("php.file-inclusion", "File inclusion from request data", "Path Traversal", S.CRITICAL,
       C.HIGH, "CWE-98", PHP,
       rf"\b(?:include|require)(?:_once)?\b[^;]*{_PHP_IN}",
       "include/require takes a path from user input.",
       "Local/remote file inclusion leads to code execution.",
       "Map input to a fixed allow-list of files; never include user-controlled paths.",
       expl="high"),
    mk("php.unserialize", "unserialize() on variable data", "Unsafe Deserialization", S.HIGH,
       C.MEDIUM, "CWE-502", PHP, r"\bunserialize\s*\(\s*\$",
       "unserialize() can instantiate arbitrary objects and trigger magic methods.",
       "Object injection can lead to code execution.",
       "Use json_decode; if needed pass ['allowed_classes' => false].", expl="high"),
    mk("php.reflected-xss", "Request data echoed without encoding", "Cross-Site Scripting",
       S.HIGH, C.MEDIUM, "CWE-79", PHP,
       rf"\b(?:echo|print)\b[^;]*{_PHP_IN}",
       "User input is written to the page directly.",
       "Script injected via the input runs in victims' browsers.",
       "Wrap output in htmlspecialchars($v, ENT_QUOTES, 'UTF-8').",
       unless=r"htmlspecialchars|htmlentities|intval|esc_html|esc_attr|(?:int)\s*\$",
       expl="high"),
    mk("php.weak-hash", "Weak hash (md5/sha1)", "Insecure Cryptography", S.MEDIUM, C.MEDIUM,
       "CWE-327", PHP, r"\b(?:md5|sha1)\s*\(",
       "md5()/sha1() are unsuitable for security purposes.",
       "Hashes can be cracked quickly; passwords exposed.",
       "Use password_hash()/password_verify() for passwords, hash('sha256', ...) for integrity.",
       expl="low"),
    mk("php.path-traversal", "File operation on request data", "Path Traversal", S.HIGH, C.MEDIUM,
       "CWE-22", PHP,
       rf"\b(?:file_get_contents|fopen|readfile|file|unlink|move_uploaded_file|copy)\s*\([^;]*{_PHP_IN}",
       "A file function receives a path from user input.",
       "Attackers can read/overwrite files outside the intended directory.",
       "Use basename() and verify realpath() stays in an allowed directory.", expl="high"),
    mk("php.extract-request", "extract() on request data", "Insecure Defaults", S.HIGH, C.HIGH,
       "CWE-621", PHP, rf"\bextract\s*\(\s*{_PHP_IN}",
       "extract() creates variables from user input, overwriting existing ones.",
       "Attackers can overwrite application variables (authentication flags, paths).",
       "Read specific keys explicitly instead of extract()."),
    mk("php.open-redirect", "Redirect to request-supplied location", "Open Redirect", S.MEDIUM,
       C.MEDIUM, "CWE-601", PHP, rf"header\s*\(\s*[\"']Location:[^;]*{_PHP_IN}",
       "A Location header is built from user input.", "Phishing via a trusted domain.",
       "Redirect only to allow-listed or relative destinations."),
    mk("php.tls-verification-disabled", "TLS verification disabled", "Insecure Transport",
       S.HIGH, C.HIGH, "CWE-295", PHP,
       r"CURLOPT_SSL_VERIFY(?:PEER|HOST)\s*,\s*(?:false|0)|[\"']verify_peer[\"']\s*=>\s*false",
       "Certificate validation is disabled for a request.",
       "Connections can be intercepted.", "Remove the override and fix trust configuration.",
       expl="medium"),
    # ---- Ruby -------------------------------------------------------------------------------
    mk("rb.eval", "Dynamic code evaluation", "Code Injection", S.HIGH, C.MEDIUM, "CWE-95", RB,
       r"\b(?:eval|instance_eval|class_eval|module_eval)(?:\s*\(\s*|\s+)(?=\S)"
       r"(?![\"'][^\"'#]*[\"']\s*\)?\s*$)",
       "eval and friends execute strings as Ruby code.",
       "Attacker input leads to remote code execution.",
       "Avoid eval; use explicit dispatch (a hash of allowed methods).", expl="high"),
    mk("rb.command-injection", "Shell command with interpolation", "Command Injection", S.HIGH,
       C.MEDIUM, "CWE-78", RB,
       r"\b(?:system|exec|spawn|popen|IO\.popen)\s*\(?\s*\"[^\"]*#\{|`[^`]*#\{|%x[\[{(][^\]})]*#\{",
       "A shell command string includes interpolated values.",
       "Input can inject additional commands.",
       "Use the multi-argument form: system('ls', dir), which bypasses the shell.", expl="high"),
    mk("rb.sql-injection", "SQL fragment built with interpolation", "SQL Injection", S.HIGH,
       C.MEDIUM, "CWE-89", RB,
       r"\.(?:where|find_by_sql|order|group|joins|select|execute|exists\?|having)\s*\(?\s*\"[^\"]*#\{",
       "ActiveRecord receives an interpolated SQL string.",
       "An attacker can alter the query.",
       "Use placeholders: where('name = ?', name) or hash conditions.", expl="high"),
    mk("rb.unsafe-deserialization", "Unsafe deserialization (Marshal / YAML.load)",
       "Unsafe Deserialization", S.HIGH, C.MEDIUM, "CWE-502", RB,
       r"\b(?:Marshal\.load|Marshal\.restore|YAML\.load|Psych\.load)\s*\(",
       "These loaders can instantiate arbitrary objects.",
       "Untrusted input can lead to code execution.",
       "Use YAML.safe_load / JSON.parse for untrusted data.", expl="high"),
    mk("rb.html-safe", "Output marked HTML-safe", "Cross-Site Scripting", S.MEDIUM, C.LOW,
       "CWE-79", RB, r"\.html_safe\b|\braw\s*\(?\s*(?:params|@\w+)",
       "html_safe/raw disables Rails output escaping.",
       "Untrusted content becomes executable script.",
       "Remove html_safe/raw or sanitise with the sanitize helper."),
    mk("rb.mass-assignment", "params.permit! allows all attributes", "Authorization", S.HIGH,
       C.HIGH, "CWE-915", RB, r"\.permit!",
       "Strong parameters are bypassed by permitting every attribute.",
       "Attackers can set privileged fields such as roles or ownership.",
       "Permit an explicit list of attributes."),
    mk("rb.open-redirect", "redirect_to with params", "Open Redirect", S.MEDIUM, C.MEDIUM,
       "CWE-601", RB, r"redirect_to\s+params\[",
       "The redirect target comes from the request.", "Phishing via a trusted domain.",
       "Redirect to allow-listed paths or use only_path: true."),
    mk("rb.path-traversal", "File access using params", "Path Traversal", S.HIGH, C.MEDIUM,
       "CWE-22", RB,
       r"(?:File\.(?:read|open|write|delete|readlines)|send_file|IO\.read)\s*\(?[^\n]*params\[",
       "A file path is taken from request parameters.",
       "Attackers can read files outside the intended directory.",
       "Use File.basename and check the expanded path lies under a base directory.",
       expl="high"),
    mk("rb.weak-hash", "Weak hash (MD5 / SHA-1)", "Insecure Cryptography", S.MEDIUM, C.HIGH,
       "CWE-327", RB, r"Digest::(?:MD5|SHA1)\b",
       "MD5/SHA-1 are broken.", "Hashes can be forged or cracked.",
       "Use Digest::SHA256 and bcrypt for passwords.", expl="low"),
    mk("rb.csrf-skipped", "CSRF protection skipped", "Authorization", S.MEDIUM, C.MEDIUM,
       "CWE-352", RB,
       r"skip_before_action\s+:verify_authenticity_token|protect_from_forgery\s+with:\s*:null_session",
       "CSRF verification is disabled.", "State-changing requests can be forged.",
       "Keep authenticity-token verification enabled for browser sessions."),
    mk("rb.tls-verification-disabled", "TLS verification disabled", "Insecure Transport", S.HIGH,
       C.HIGH, "CWE-295", RB, r"OpenSSL::SSL::VERIFY_NONE|verify_ssl\s*[:=]>?\s*false",
       "Certificate verification is off.", "Connections can be intercepted.",
       "Use VERIFY_PEER with the system CA store.", expl="medium"),
    # ---- Shell ------------------------------------------------------------------------------
    mk("sh.curl-pipe-shell", "Downloaded script piped to a shell", "Supply Chain", S.MEDIUM,
       C.MEDIUM, "CWE-494", SH, r"(?:curl|wget)\b[^|\n]*\|\s*(?:sudo\s+)?(?:ba|z)?sh\b",
       "A remote script is executed without verification.",
       "A compromised or tampered download runs with your privileges.",
       "Download, verify a checksum/signature, review, then execute.", expl="low"),
    mk("sh.chmod-777", "World-writable permissions", "Insecure File Operations", S.MEDIUM,
       C.HIGH, "CWE-732", SH, r"\bchmod\s+(?:-R\s+)?0?777\b",
       "chmod 777 makes files writable by everyone.",
       "Local users can modify or replace the files.",
       "Grant the minimum permissions (e.g. 750/640).", expl="low"),
    mk("sh.eval-variable", "eval on a variable", "Command Injection", S.MEDIUM, C.MEDIUM,
       "CWE-78", SH, r"\beval\s+[\"']?\$",
       "eval executes the contents of a variable as shell code.",
       "Attacker-influenced values lead to command injection.",
       "Avoid eval; use arrays and \"${array[@]}\" expansion.", expl="medium"),
    mk("sh.tls-verification-disabled", "TLS verification disabled in download", "Insecure Transport",
       S.MEDIUM, C.HIGH, "CWE-295", SH,
       r"\bcurl\b[^\n]*\s(?:-k|--insecure)\b|\bwget\b[^\n]*--no-check-certificate",
       "Certificate checks are turned off for a download.",
       "The download can be intercepted or replaced.",
       "Remove -k/--no-check-certificate and trust the right CA.", expl="low"),
]
