"""JavaScript / TypeScript rules."""

from __future__ import annotations

from netguard.enums import Confidence as C
from netguard.enums import Severity as S
from netguard.scanners.sast.rules import Rule, owasp, rx

JS = ("javascript", "typescript")
_REQ = r"req(?:uest)?\.(?:query|params|body|headers|cookies)"
_SQL_WORDS = r"\b(?:select|insert\s+into|update|delete\s+from)\b"

RULES: list[Rule] = [
    Rule(
        id="js.eval",
        title="Use of eval() / Function constructor",
        category="Code Injection",
        severity=S.HIGH,
        confidence=C.MEDIUM,
        cwe="CWE-95",
        languages=JS,
        pattern=rx(r"(?<![\w.$])eval\s*\(\s*(?=\S)(?!['\"`][^'\"`]*['\"`]\s*\))|new\s+Function\s*\("),
        description="eval() or the Function constructor executes a string as code.",
        impact="If any part of the string is attacker-controlled, the attacker can run arbitrary "
        "JavaScript in your application.",
        remediation="Avoid dynamic code execution. Use JSON.parse for data, or lookup tables / "
        "explicit functions for behaviour selection.",
        exploitability="high",
        references=(owasp("attacks/Code_Injection"),),
    ),
    Rule(
        id="js.command-injection",
        title="OS command built from a dynamic string",
        category="Command Injection",
        severity=S.HIGH,
        confidence=C.MEDIUM,
        cwe="CWE-78",
        languages=JS,
        pattern=rx(
            r"(?:(?<![\w$.])|child_process\.|cp\.)(?:exec|execSync)\s*\(\s*"
            r"(?:`[^`]*\$\{|['\"][^'\"]*['\"]\s*\+|[A-Za-z_$][\w$.]*\s*[,)])"
        ),
        description="A shell command is passed to exec()/execSync() using a template string, "
        "concatenation or a variable. exec() runs the string through a shell.",
        impact="Attacker-controlled input can inject extra shell commands and run arbitrary "
        "commands with the application's privileges.",
        remediation="Use execFile()/spawn() with an argument array and shell disabled, and "
        "validate inputs against an allow-list.",
        exploitability="high",
        references=(owasp("attacks/Command_Injection"),),
    ),
    Rule(
        id="js.sql-injection",
        title="SQL query built with string interpolation",
        category="SQL Injection",
        severity=S.HIGH,
        confidence=C.MEDIUM,
        cwe="CWE-89",
        languages=JS,
        pattern=rx(
            rf"(?:query|execute|raw)\s*\(\s*(?:`[^`]*{_SQL_WORDS}[^`]*\$\{{|"
            rf"\"[^\"]*{_SQL_WORDS}[^\"]*\"\s*\+|'[^']*{_SQL_WORDS}[^']*'\s*\+)",
            2,  # re.IGNORECASE
        ),
        description="A SQL statement is assembled from variables via a template literal or "
        "string concatenation and passed to the database driver.",
        impact="An attacker can alter the query to read, modify or delete data they should not "
        "have access to.",
        remediation="Use parameterized queries / prepared statements (for example "
        "db.query('SELECT ... WHERE id = $1', [id])) or a query builder.",
        exploitability="high",
        references=(owasp("attacks/SQL_Injection"),),
    ),
    Rule(
        id="js.nosql-injection",
        title="Request data passed directly to a MongoDB query",
        category="NoSQL Injection",
        severity=S.MEDIUM,
        confidence=C.MEDIUM,
        cwe="CWE-943",
        languages=JS,
        pattern=rx(rf"\.(?:find|findOne|updateOne|updateMany|deleteOne|deleteMany)\s*\(\s*{_REQ}\b"),
        description="An entire request object (body/query) is used as a database filter.",
        impact="Operators such as $ne or $gt in user input can bypass filters or authentication.",
        remediation="Validate the shape of input, cast values to expected primitive types and "
        "build the filter explicitly from known fields.",
        exploitability="medium",
    ),
    Rule(
        id="js.innerhtml",
        title="Assignment to innerHTML / outerHTML",
        category="Cross-Site Scripting",
        severity=S.MEDIUM,
        confidence=C.MEDIUM,
        cwe="CWE-79",
        languages=JS,
        pattern=rx(
            r"\.(?:innerHTML|outerHTML)\s*\+?=\s*(?=\S)"
            r"(?:(?!['\"`])|['\"`][^'\"`]*(?:\$\{|['\"`]\s*\+))"
        ),
        description="Content assigned to innerHTML/outerHTML is parsed as HTML.",
        impact="If the value contains untrusted data, an attacker can inject script and act as "
        "the user (session theft, actions on their behalf).",
        remediation="Assign to textContent for plain text, or sanitise HTML with a vetted library "
        "such as DOMPurify before insertion.",
        exploitability="high",
        fixer="js.innerhtml",
        references=(owasp("attacks/xss/"),),
    ),
    Rule(
        id="js.document-write",
        title="Use of document.write()",
        category="Cross-Site Scripting",
        severity=S.MEDIUM,
        confidence=C.MEDIUM,
        cwe="CWE-79",
        languages=JS,
        pattern=rx(r"document\.write(?:ln)?\s*\(\s*(?=\S)(?!['\"`][^'\"`$]*['\"`]\s*\))|insertAdjacentHTML\s*\("),
        description="document.write()/insertAdjacentHTML() inject raw HTML into the page.",
        impact="Untrusted data reaching these sinks enables DOM-based XSS.",
        remediation="Create elements with DOM APIs and set textContent, or sanitise first.",
        exploitability="high",
    ),
    Rule(
        id="js.react-dangerously-set-html",
        title="dangerouslySetInnerHTML used",
        category="Cross-Site Scripting",
        severity=S.MEDIUM,
        confidence=C.LOW,
        cwe="CWE-79",
        languages=JS,
        pattern=rx(r"dangerouslySetInnerHTML"),
        description="React's dangerouslySetInnerHTML bypasses React's output escaping.",
        impact="If the HTML includes untrusted content it results in stored or reflected XSS.",
        remediation="Prefer rendering text through JSX. If HTML is required, sanitise with DOMPurify.",
        exploitability="medium",
    ),
    Rule(
        id="js.reflected-xss",
        title="Request data written directly into the response",
        category="Cross-Site Scripting",
        severity=S.HIGH,
        confidence=C.MEDIUM,
        cwe="CWE-79",
        languages=JS,
        pattern=rx(rf"res\.(?:send|write|end)\s*\(.*\b{_REQ}"),
        description="User-supplied request data is echoed in the HTTP response body.",
        impact="With an HTML content type, script in the input runs in the victim's browser.",
        remediation="Encode output for its context, return JSON via res.json(), or use a "
        "template engine with auto-escaping.",
        exploitability="high",
    ),
    Rule(
        id="js.path-traversal",
        title="File path built from request data",
        category="Path Traversal",
        severity=S.HIGH,
        confidence=C.MEDIUM,
        cwe="CWE-22",
        languages=JS,
        pattern=rx(
            r"(?:readFile|readFileSync|createReadStream|writeFile|writeFileSync|sendFile|unlink|"
            rf"readdir|path\.(?:join|resolve))\s*\([^)]*\b{_REQ}"
        ),
        description="A filesystem call receives a path derived from request input.",
        impact="Sequences like ../ let an attacker read or overwrite files outside the intended "
        "directory.",
        remediation="Resolve the final path and verify it stays inside an allowed base directory, "
        "or map user input to IDs looked up server-side.",
        exploitability="high",
        references=(owasp("attacks/Path_Traversal"),),
    ),
    Rule(
        id="js.ssrf",
        title="Outbound request to a URL taken from request data",
        category="Server-Side Request Forgery",
        severity=S.HIGH,
        confidence=C.MEDIUM,
        cwe="CWE-918",
        languages=JS,
        pattern=rx(rf"(?:axios(?:\.\w+)?|fetch|got|request|http\.get|https\.get)\s*\(\s*{_REQ}"),
        description="The server fetches a URL supplied by the client.",
        impact="Attackers can make the server reach internal services or cloud metadata endpoints.",
        remediation="Validate against an allow-list of hosts, block private/link-local ranges and "
        "disable redirects to untrusted destinations.",
        exploitability="medium",
    ),
    Rule(
        id="js.open-redirect",
        title="Redirect to a user-controlled URL",
        category="Open Redirect",
        severity=S.MEDIUM,
        confidence=C.MEDIUM,
        cwe="CWE-601",
        languages=JS,
        pattern=rx(rf"res\.redirect\s*\(\s*{_REQ}"),
        description="The response redirects to a location from the request.",
        impact="Used for phishing: a trusted domain redirects victims to a malicious site.",
        remediation="Only redirect to relative paths or an allow-list of known destinations.",
        exploitability="medium",
    ),
    Rule(
        id="js.weak-hash",
        title="Weak hash algorithm (MD5 / SHA-1)",
        category="Insecure Cryptography",
        severity=S.MEDIUM,
        confidence=C.HIGH,
        cwe="CWE-327",
        languages=JS,
        pattern=rx(r"createHash\(\s*['\"](?:md5|sha1)['\"]", 2),
        description="MD5 and SHA-1 are broken for collision resistance and unsuitable for passwords.",
        impact="Hashes can be forged or cracked quickly; unsafe for integrity or password storage.",
        remediation="Use SHA-256/SHA-512 for integrity and a password hash (bcrypt, scrypt, "
        "argon2) for passwords.",
        exploitability="low",
        fixer="js.weak-hash",
    ),
    Rule(
        id="js.insecure-random",
        title="Math.random() used for a security value",
        category="Insecure Randomness",
        severity=S.MEDIUM,
        confidence=C.MEDIUM,
        cwe="CWE-338",
        languages=JS,
        pattern=rx(r"(?=.*(?:token|secret|password|passwd|session|nonce|apikey|api_key|csrf|otp\b))"
                   r".*Math\.random\s*\(", 2),
        description="Math.random() is not a cryptographically secure generator.",
        impact="Tokens or identifiers can be predicted by an attacker.",
        remediation="Use crypto.randomBytes()/crypto.randomUUID() (Node) or crypto.getRandomValues().",
        exploitability="medium",
    ),
    Rule(
        id="js.tls-verification-disabled",
        title="TLS certificate verification disabled",
        category="Insecure Transport",
        severity=S.HIGH,
        confidence=C.HIGH,
        cwe="CWE-295",
        languages=JS,
        pattern=rx(r"rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['\"]?0"),
        description="Certificate validation for outgoing TLS connections is turned off.",
        impact="Connections can be intercepted and modified by a man-in-the-middle.",
        remediation="Remove the override and fix the underlying certificate problem (trust the "
        "correct CA instead of disabling validation).",
        exploitability="medium",
        fixer="js.tls-verification-disabled",
    ),
    Rule(
        id="js.jwt-insecure",
        title="Insecure JWT verification settings",
        category="Insecure Authentication",
        severity=S.HIGH,
        confidence=C.HIGH,
        cwe="CWE-347",
        languages=JS,
        pattern=rx(r"algorithms?\s*:\s*\[?\s*['\"]none['\"]|ignoreExpiration\s*:\s*true", 2),
        description="JWTs are accepted with the 'none' algorithm or without expiry checks.",
        impact="Attackers can forge tokens or reuse expired tokens to impersonate users.",
        remediation="Pin an explicit strong algorithm (e.g. HS256/RS256) and always verify expiry.",
        exploitability="high",
    ),
    Rule(
        id="js.hardcoded-credential-check",
        title="Credential compared to a hard-coded value",
        category="Insecure Authentication",
        severity=S.HIGH,
        confidence=C.MEDIUM,
        cwe="CWE-798",
        languages=JS,
        pattern=rx(r"\b(?:password|passwd|pwd|secret|token)\s*===?\s*['\"][^'\"]{3,}['\"]", 2),
        description="Authentication logic compares a credential against a literal in source code.",
        impact="Anyone with the source (or who guesses it) can authenticate; rotation needs a deploy.",
        remediation="Store credentials as salted password hashes in a datastore or secret manager.",
        exploitability="high",
    ),
    Rule(
        id="js.insecure-cookie",
        title="Session cookie without HttpOnly/Secure",
        category="Insecure Authentication",
        severity=S.MEDIUM,
        confidence=C.MEDIUM,
        cwe="CWE-614",
        languages=JS,
        pattern=rx(r"\b(?:httpOnly|secure)\s*:\s*false"),
        description="A cookie flag that protects the session cookie is explicitly disabled.",
        impact="Scripts can read the cookie (XSS) or it can be sent over plaintext HTTP.",
        remediation="Set httpOnly: true, secure: true and an appropriate sameSite value.",
        exploitability="medium",
    ),
    Rule(
        id="js.cors-permissive",
        title="Permissive CORS configuration",
        category="Authorization",
        severity=S.MEDIUM,
        confidence=C.MEDIUM,
        cwe="CWE-942",
        languages=JS,
        pattern=rx(r"cors\(\s*\{[^}]*origin\s*:\s*(?:true|['\"]\*['\"])"),
        description="CORS allows any origin to read responses.",
        impact="Malicious sites can read authenticated API responses from a visitor's browser.",
        remediation="Restrict origin to an explicit allow-list; never combine wildcard origins with credentials.",
        exploitability="medium",
    ),
    Rule(
        id="js.unsafe-deserialization",
        title="Unsafe deserialization (node-serialize)",
        category="Unsafe Deserialization",
        severity=S.CRITICAL,
        confidence=C.HIGH,
        cwe="CWE-502",
        languages=JS,
        pattern=rx(r"require\(\s*['\"]node-serialize['\"]\s*\)|\bserialize\.unserialize\s*\("),
        description="node-serialize's unserialize() executes functions embedded in its input.",
        impact="Attacker-controlled data leads directly to remote code execution.",
        remediation="Use JSON.parse for data interchange. Never deserialize untrusted input into code.",
        exploitability="high",
    ),
    Rule(
        id="js.vm-context",
        title="Dynamic code run through the vm module",
        category="Code Injection",
        severity=S.HIGH,
        confidence=C.MEDIUM,
        cwe="CWE-94",
        languages=JS,
        pattern=rx(r"\bvm\.(?:runInNewContext|runInThisContext|runInContext|compileFunction)\s*\("),
        description="The vm module is not a security sandbox.",
        impact="Untrusted code can escape the context and gain full process access.",
        remediation="Do not run untrusted code in-process; use OS-level isolation or a dedicated sandbox.",
        exploitability="medium",
    ),
    Rule(
        id="js.prototype-pollution",
        title="Possible prototype pollution",
        category="Prototype Pollution",
        severity=S.MEDIUM,
        confidence=C.LOW,
        cwe="CWE-1321",
        languages=JS,
        pattern=rx(r"\[\s*['\"]__proto__['\"]\s*\]|\.__proto__\s*="),
        description="Code manipulates __proto__ directly.",
        impact="Modifying Object.prototype can change application behaviour globally.",
        remediation="Reject __proto__/constructor/prototype keys, use Object.create(null) or Map.",
        exploitability="medium",
    ),
    Rule(
        id="js.file-permissions",
        title="Overly permissive file mode (0777)",
        category="Insecure File Operations",
        severity=S.MEDIUM,
        confidence=C.HIGH,
        cwe="CWE-732",
        languages=JS,
        pattern=rx(r"(?:chmod|chmodSync|mkdir|mkdirSync|writeFile|writeFileSync)\s*\([^)]*0o?777"),
        description="A file or directory is created with world-writable permissions.",
        impact="Other local users or processes can modify or replace the file.",
        remediation="Use the least permissive mode needed (for example 0o600 for files, 0o700 for directories).",
        exploitability="low",
    ),
]
