"""Rule metadata for the API security scanner."""

from __future__ import annotations

from netguard.enums import Confidence as C
from netguard.enums import Severity as S
from netguard.scanners.iac.meta import R

CAT = "API Security"
AUTH = "Broken Authentication"

RULES = {r.id: r for r in [
    R("api.auth-not-enforced", "Protected endpoint accessible without credentials", AUTH, S.HIGH, C.HIGH,
      "CWE-306", "The specification declares this operation as requiring authentication, but it "
      "returned a success response to a request that carried no credentials.",
      "Anyone can call an endpoint that is supposed to be protected.",
      "Enforce authentication in middleware for every protected route (deny by default).", expl="high"),
    R("api.invalid-credentials-accepted", "Invalid credentials accepted", AUTH, S.HIGH, C.HIGH, "CWE-287",
      "A deliberately invalid credential was accepted with a success response.",
      "Authentication can be bypassed with arbitrary tokens.",
      "Validate every token (signature, expiry, audience) before processing requests.", expl="high"),
    R("api.public-endpoints", "Endpoints accessible without authentication", CAT, S.INFO, C.HIGH, "CWE-306",
      "These read-only endpoints responded successfully with no credentials. This may be intended.",
      "Unintended public data exposure if any of them should be protected.",
      "Review each listed endpoint and confirm it is meant to be public."),
    R("api.plaintext-http", "API served over plaintext HTTP", CAT, S.MEDIUM, C.HIGH, "CWE-319",
      "The API is reachable over HTTP without TLS.",
      "Tokens, credentials and data can be intercepted or altered in transit.",
      "Serve the API over HTTPS only and redirect or reject HTTP."),
    R("api.tls-legacy-protocol", "Legacy TLS versions supported", CAT, S.MEDIUM, C.HIGH, "CWE-327",
      "The server completed a handshake using TLS 1.0 or 1.1.",
      "Deprecated protocol versions have known weaknesses.",
      "Disable TLS 1.0/1.1; require TLS 1.2 or newer."),
    R("api.tls-certificate", "TLS certificate problem", CAT, S.MEDIUM, C.HIGH, "CWE-295",
      "The presented certificate failed validation (expired, self-signed, wrong host or untrusted).",
      "Clients cannot verify they are talking to the real API.",
      "Install a valid certificate from a trusted CA and automate renewal."),
    R("api.tls-cert-expiring", "TLS certificate expires soon", CAT, S.LOW, C.HIGH, "CWE-298",
      "The certificate expires within 14 days.", "An unexpected expiry will cause an outage.",
      "Renew the certificate and automate renewal."),
    R("api.missing-hsts", "HSTS header missing", CAT, S.LOW, C.MEDIUM, "CWE-319",
      "Responses over HTTPS lack Strict-Transport-Security.",
      "Browsers may be downgraded to HTTP by an on-path attacker.",
      "Send Strict-Transport-Security: max-age=31536000; includeSubDomains."),
    R("api.missing-nosniff", "X-Content-Type-Options header missing", CAT, S.LOW, C.MEDIUM, "CWE-693",
      "Responses lack X-Content-Type-Options: nosniff.",
      "Browsers may interpret responses as a different content type.",
      "Send X-Content-Type-Options: nosniff on every response."),
    R("api.version-disclosure", "Server technology disclosed", CAT, S.INFO, C.HIGH, "CWE-200",
      "Response headers reveal the server software or framework version.",
      "Helps attackers target known vulnerabilities in that version.",
      "Remove or genericise Server / X-Powered-By headers."),
    R("api.cors-reflects-origin-credentials", "CORS reflects any origin with credentials", CAT, S.HIGH,
      C.HIGH, "CWE-942", "An arbitrary Origin was echoed in Access-Control-Allow-Origin together "
      "with Access-Control-Allow-Credentials: true.",
      "Any website can make authenticated requests as the visiting user and read the responses.",
      "Allow only an explicit list of trusted origins.", expl="high"),
    R("api.cors-wildcard", "CORS allows any origin", CAT, S.LOW, C.MEDIUM, "CWE-942",
      "Access-Control-Allow-Origin is * (without credentials).",
      "Any website can read responses; fine for genuinely public data, risky otherwise.",
      "Restrict to trusted origins unless the API is intentionally public."),
    R("api.no-rate-limiting", "No rate limiting observed", CAT, S.LOW, C.LOW, "CWE-770",
      "A short burst of requests produced no 429 responses and no rate-limit headers. "
      "Limits may still exist at another layer (gateway, WAF).",
      "Without limits the API is easier to brute-force and to overload.",
      "Apply per-client rate limits and return 429 with Retry-After."),
    R("api.verbose-errors", "Verbose error messages / stack traces", CAT, S.MEDIUM, C.HIGH, "CWE-209",
      "An error response contained internal details (stack trace, SQL error or framework debug info).",
      "Internal implementation details help attackers craft targeted attacks.",
      "Return generic error messages and log details server-side; disable debug mode."),
    R("api.server-error-on-bad-input", "Server error on malformed input", CAT, S.LOW, C.MEDIUM, "CWE-20",
      "Malformed but harmless input caused a 5xx response.",
      "Unhandled input can indicate missing validation and sometimes exploitable bugs.",
      "Validate input types, lengths and formats and return 4xx for invalid requests."),
    R("api.trace-enabled", "HTTP TRACE method enabled", CAT, S.MEDIUM, C.MEDIUM, "CWE-16",
      "The server advertises the TRACE method.", "TRACE can aid cross-site tracing attacks.",
      "Disable TRACE."),
    R("api.insecure-cookie", "Cookie missing security attributes", CAT, S.MEDIUM, C.HIGH, "CWE-614",
      "A Set-Cookie header lacks Secure and/or HttpOnly.",
      "Cookies can be read by scripts or sent over plaintext HTTP.",
      "Set Secure, HttpOnly and SameSite on session cookies."),
    R("api.jwt-none", "JWT uses the 'none' algorithm", AUTH, S.CRITICAL, C.HIGH, "CWE-347",
      "The supplied token's header declares alg: none (unsigned).",
      "Unsigned tokens can be forged by anyone.", "Reject unsigned tokens; pin an algorithm."),
    R("api.jwt-no-expiry", "JWT has no expiry", AUTH, S.LOW, C.HIGH, "CWE-613",
      "The supplied token has no 'exp' claim.", "A leaked token stays valid forever.",
      "Issue short-lived tokens with exp and support revocation."),
    R("api.spec-plaintext-server", "Specification lists HTTP servers", CAT, S.LOW, C.HIGH, "CWE-319",
      "The OpenAPI 'servers' list includes a non-TLS URL.",
      "Clients following the spec may send data unencrypted.", "List only https:// servers."),
    R("api.spec-no-security", "Operation declares no security requirement", AUTH, S.MEDIUM, C.MEDIUM,
      "CWE-306", "This state-changing operation has no security requirement in the specification. "
      "NetGuard did not call it (write endpoints are never invoked).",
      "If the implementation matches the spec, anyone can modify data.",
      "Add a security requirement, or document why the operation is public."),
    R("api.spec-weak-scheme", "Weak authentication scheme declared", AUTH, S.MEDIUM, C.HIGH, "CWE-522",
      "The specification uses HTTP Basic auth or an API key passed in the query string.",
      "Credentials in URLs are logged and cached; Basic auth sends static secrets on every call.",
      "Prefer OAuth 2 / bearer tokens sent in the Authorization header."),
    R("api.spec-sensitive-query-param", "Sensitive value passed in the query string", CAT, S.MEDIUM,
      C.MEDIUM, "CWE-598", "A parameter named like a secret is sent in the URL query.",
      "URLs appear in logs, browser history and referrers.",
      "Send secrets in headers or the request body."),
]}
